### ISSUE TITLE
1.4.5 build fails

### ISSUE THREAD

**Issue by eeickmeyer** [ChurchApps/FreeShow#1759]
I'm running a bit behind and somehow missed the 1.4.5 release. When attempting to build, I'm running into an error and it's failing.

Just to note, I did a this using a clean clone of the repository and `git checkout v1.4.5` before running the `makesnap` script.

```
src/frontend/main.ts → public/build/bundle.js...
[!] (plugin typescript) RollupError: Could not load /home/erich/freeshow/src/frontend/components/helpers/output.ts (imported by src/frontend/App.svelte): [plugin typescript] src/frontend/IPC/main.ts (33:16): @rollup/plugin-typescript TS2339: Property 'api' does not exist on type 'Window & typeof globalThis'.
src/frontend/IPC/main.ts (33:16)

33         window.api.receive(
                  ~~~

    at getRollupError (/home/erich/freeshow/node_modules/rollup/dist/shared/parseAst.js:285:41)
    at Object.error (/home/erich/freeshow/node_modules/rollup/dist/shared/parseAst.js:281:42)
    at Object.error (/home/erich/freeshow/node_modules/rollup/dist/shared/rollup.js:913:32)
    at emitDiagnostic (file:///home/erich/freeshow/node_modules/@rollup/plugin-typescript/dist/es/index.js:554:17)
    at reportDiagnostics (file:///home/erich/freeshow/node_modules/@rollup/plugin-typescript/dist/es/index.js:562:9)
    at Array.forEach (<anonymous>)
    at emitFilesAndReportErrors (/home/erich/freeshow/node_modules/typescript/lib/typescript.js:126138:21)
    at Object.result.afterProgramCreate (/home/erich/freeshow/node_modules/typescript/lib/typescript.js:126329:13)
    at Object.afterProgramCreate (file:///home/erich/freeshow/node_modules/@rollup/plugin-typescript/dist/es/index.js:721:29)
    at synchronizeProgram (/home/erich/freeshow/node_modules/typescript/lib/typescript.js:126639:22)


ERROR: "build:frontend:prod" exited with 1.
```

**Comment by vassbo** [comment]
No worries. I think some package updated, and broke typescript, so I tried adding back the `package-lock` file. You can copy the `package-lock` file from the main branch, and it should work in 1.4.5 as well.

**Comment by eeickmeyer** [comment]
Sadly, it did not work. I managed to get 1.4.6-beta.1 to build with that package-lock file, but not 1.4.5.

**Comment by eeickmeyer** [comment]
Nevermind. I got it to work but only after re-using the `node_modules` directory from the 1.4.6-beta.1 build. Felt super hacky, but it bypassed the dep issues.

**Comment by vassbo** [comment]
Nice! I hope you don't run into package issues like this again, I think it's fine as long as I got the package-lock file. But the reason I removed it was because there was a NPM Rollup issue with GitHub Actions, but it seems to be gone or random.
